<?php
    $gpio_onoff = isset($_POST['gpio_onoff']) ? $_POST['gpio_onoff'] : '';
    $gpio_onoff1 = isset($_POST['gpio_onoff1']) ? $_POST['gpio_onoff1'] : '';
    if (($gpio_onoff1 == "gpio_onoff2") ){
		$db = new PDO('sqlite:dbf/nettemp.db');
		$db->exec("UPDATE nt_settings SET value='$gpio_onoff' WHERE option='gpio'") or die ($db->lastErrorMsg());
		echo $gpio_onoff;
		header("location: " . $_SERVER['REQUEST_URI']);
		exit();
    }
    
    $MCP23017_onoff = isset($_POST['MCP23017_onoff']) ? $_POST['MCP23017_onoff'] : '';
    $MCP23017_onoff1 = isset($_POST['MCP23017_onoff1']) ? $_POST['MCP23017_onoff1'] : '';
    if (($MCP23017_onoff1 == "MCP23017_onoff2") ){
		$db = new PDO('sqlite:dbf/nettemp.db');
		$db->exec("UPDATE nt_settings SET value='$MCP23017_onoff' WHERE option='MCP23017'") or die ($db->lastErrorMsg());
		header("location: " . $_SERVER['REQUEST_URI']);
		exit();
    }
	
	$screen_onoff = isset($_POST['screen_onoff']) ? $_POST['screen_onoff'] : '';
    $screen_onoff1 = isset($_POST['screen_onoff1']) ? $_POST['screen_onoff1'] : '';
    if (($screen_onoff1 == "screen_onoff2") ){
    $db->exec("UPDATE nt_settings SET value='$screen_onoff' WHERE option='screen'") or die ($db->lastErrorMsg());
    header("location: " . $_SERVER['REQUEST_URI']);
    exit();
    }

	$map_onoff = isset($_POST['map_onoff']) ? $_POST['map_onoff'] : '';
    $map_onoff1 = isset($_POST['map_onoff1']) ? $_POST['map_onoff1'] : '';
    if (($map_onoff1 == "map_onoff2") ){
    $db->exec("UPDATE nt_settings SET value='$map_onoff' WHERE option='mapon'") or die ($db->lastErrorMsg());
    header("location: " . $_SERVER['REQUEST_URI']);
    exit();
    }
	
	$ntp_onoff = isset($_POST['ntp_onoff']) ? $_POST['ntp_onoff'] : '';
    $rtc_onoff = isset($_POST['rtc_onoff']) ? $_POST['rtc_onoff'] : '';
    $rtc = isset($_POST['rtc']) ? $_POST['rtc'] : '';
    $ntp = isset($_POST['ntp']) ? $_POST['ntp'] : '';

    if (($ntp_onoff == "ntp_onoff") ){
    if (!empty($ntp)) {
	shell_exec("sudo service ntp start");
        shell_exec("sudo update-rc.d ntp enable ");
    }
    else {	
	shell_exec("sudo service ntp stop");
        shell_exec("sudo update-rc.d ntp disable ");
    } 
    header("location: " . $_SERVER['REQUEST_URI']);
    exit();
    }
                
    if (($rtc_onoff == "rtc_onoff") ){
    if (!empty($rtc)) {
	    $file='tmp/cronr';
	    if (filesize($file) == 0){
		$current = file_get_contents($file);
		$current = "#crontab file generated by php\n";
		file_put_contents($file, $current);
	    }
		
	    shell_exec("sudo sed -i '\$artc-ds1307' /etc/modules");
	    shell_exec("sudo sed -i '\$aecho ds1307 0x68 > \/sys\/class\/i2c-adapter\/'$(ls /dev/i2c-* |awk -F/ '{print $3}')'\/new_device && hwclock -s' tmp/cronr");
	    shell_exec("sudo touch tmp/reboot");
    }
    else {
	shell_exec("sudo sed -i '/ds1307/d' tmp/cronr");
        shell_exec("sudo sed -i '/rtc-ds1307/d' /etc/modules");
	} 
    header("location: " . $_SERVER['REQUEST_URI']);
    exit();
    }
	
	
	if (exec("cat /etc/modules | grep 'ds1307'") &&  exec("cat tmp/cronr | grep 'ds1307'")) {
		$rtc='on';
	} else {
		$rtc='';
		//echo "module not added or autostart";
	}


	if (exec("sudo service ntp status |grep 'running'")) {
	$ntp='on';
	}
	else {
	$ntp='';
	}



?>



 
 <div class="grid-item settings">
	<div class="panel panel-default">
		<div class="panel-heading">Global settings</div>
	
		
    <table class="table table-hover table-condensed">
		<tbody>
			<tr>
				<td> GPIO RPI
				</td>
				<td>
					<form action="" method="post">
					<input type="hidden" name="gpio_onoff1" value="gpio_onoff2"  />
					<input data-toggle="toggle" data-size="mini" onchange="this.form.submit()" type="checkbox" name="gpio_onoff" value="on"  <?php echo $nts_gpio == 'on' ? 'checked="checked"' : ''; ?> >
					</form>
				</td>
			</tr>
			
			<tr>
				<td> GPIO MCP23017
				</td>
				<td>
					<form action="" method="post">
					<input type="hidden" name="MCP23017_onoff1" value="MCP23017_onoff2"  />
					<input data-toggle="toggle" data-size="mini" onchange="this.form.submit()" type="checkbox" name="MCP23017_onoff" value="on"  <?php echo $nts_MCP23017 == 'on' ? 'checked="checked"' : ''; ?> >
					</form>
				</td>
			</tr>
			
			<tr>
				<td> Screen
				</td>
				<td>
					<form action="" method="post">
					<input type="hidden" name="screen_onoff1" value="screen_onoff2"  />
					<input data-toggle="toggle" data-size="mini" onchange="this.form.submit()" type="checkbox" name="screen_onoff" value="on"  <?php echo $nts_screen == 'on' ? 'checked="checked"' : ''; ?> >
					</form>
				</td>
			</tr>
			
			<tr>
				<td> Map
				</td>
				<td>
					<form action="" method="post">
					<input type="hidden" name="map_onoff1" value="map_onoff2"  />
					<input data-toggle="toggle" data-size="mini" onchange="this.form.submit()" type="checkbox" name="map_onoff" value="on"  <?php echo $nts_mapon == 'on' ? 'checked="checked"' : ''; ?> >
					</form>
				</td>
			</tr>
			
			<tr>
				<td> NTP time sync
				</td>
				<td>
					<form action="" method="post">
					<input onchange="this.form.submit()"  type="checkbox"  data-toggle="toggle" data-size="mini"  name="ntp" value="on" <?php echo $ntp == 'on' ? 'checked="checked"' : ''; ?> />
					<input type="hidden" name="ntp_onoff" value="ntp_onoff" />
					</form>
					<?php
					exec("pgrep ntpd", $pids);
					if(empty($pids)) { ?>
					<span class="label label-danger">NTPd not work</span>
					<?php
					}
					?>
				</td>
			</tr>
		</tbody>
	</table>
	</div>
</div>




