#!/usr/bin/python

from pymodbus.client.sync import ModbusSerialClient as ModbusClient
from time import strftime
import time
import sys
import subprocess

if len(sys.argv) > 1:
    getusb = sys.argv[1]
if len(sys.argv) > 2:
    addr = int(sys.argv[2], 16)
if len(sys.argv) > 3:
    brate = sys.argv[3]

client = ModbusClient(method='rtu', port=getusb, baudrate=brate, stopbits=1, parity='N', bytesize=8, timeout=1)
client.connect()

rr = client.read_holding_registers(0,15, unit=addr)
value=rr.registers
orwe_v=float(value[0])/10
orwe_a=float(value[1])/10
orwe_hz=float(value[2])/10
orwe_w=float(value[3])
orwe_var=float(value[4])
orwe_va=float(value[5])
orwe_cosfi=float(value[6])/1000
orwe_wh=float(value[8])
orwe_varh=float(value[10])
client.close()

print 'orwe_v %s' %orwe_v
print 'orwe_a %s' %orwe_a
print 'orwe_hz %s' %orwe_hz
print 'orwe_w %s' %orwe_w
print 'orwe_var %s' %orwe_var
print 'orwe_va %s' %orwe_va
print 'orwe_cosfi %s' %orwe_cosfi
print 'orwe_wh %s' %orwe_wh
print 'orwe_varh %s' %orwe_varh
